### PR TITLE
UI theming - major style update

### PR DESCRIPTION
**Pull request by SteveRobinson99**
Extends dark mode to most components in the App by using context. 
Applies toggle-able dark mode to map.
Moves More Trip Options up next to origin/destination, saving a line for larger map space.
Applies new styling to all buttons (the curved purple ones), including ones on login screen. Adds a introduction text to login screen.

### CODE REVIEW

**Comment by sirbacharach** [comment]
Would you be happy to wait until tomorrow to resolve these merge conflicts Steve? As we can all do it together then, as I think there could be some difficulties across the updates Dan has done and your updates.

**Comment by sirbacharach** [comment]
Are you happy to take a look at those merge conflicts Steve, or would you like to wait until Monday so we can do them on the morning? They don't look too difficult as it seems to be just formatting is it?

**Comment by SteveRobinson99** [comment]
> Are you happy to take a look at those merge conflicts Steve, or would you like to wait until Monday so we can do them on the morning? They don't look too difficult as it seems to be just formatting is it?

I will try sort the merge conficts, it shouldn't be much. There were no conflicts, but the recent merge will have brought one, since I made an adjustment to the GoogleMapView.

If I resolve them, am I good to merge?

**Comment by sirbacharach** [comment]
If you resolve them, let me know and I'll run it at my end to make sure everything still works before the merge.

**Comment by SteveRobinson99** [comment]
(BTW, I love the new zoom to route implementation.)

**Comment by SteveRobinson99** [comment]
I believe all conflicts are removed, and its functional for me. So please test everything and let me know if I can merge.

**Comment by SteveRobinson99** [comment]
I merged the main into the branch and removed conflicts, should be good to go now. Let me know when you tested it :)
    On Sunday, 7 January 2024 at 11:28:28 GMT, sirbacharach ***@***.***> wrote:  
 
 


If you resolve them, let me know and I'll run it at my end to make sure everything still works before the merge.

**Comment by DannyClark90** [comment]
All working fine, good to merge. Great stuff!

**Pull request merged**
