### PR TITLE
Focus map on route

### PR DESCRIPTION
**Pull request by DannyClark90**
Focus map on route functionality implemented. Autocomplete request restraints added to optimise API calls.

### CODE REVIEW

**Review by SteveRobinson99 — COMMENTED** [review]
So this pulls back only the data we need, makes sense. It should optimize performance too. Controlling costs is an added extra, nice touch.

**Review by SteveRobinson99 — COMMENTED** [review]
good

**Review by SteveRobinson99 — COMMENTED** [review]
This will zoom to the route, and is there still the icon to zoom to the users current location on the map? Looks like a nice functionality.

**Comment by SteveRobinson99** [comment]
I see no reason not to merge when you are ready.
I think you requested a review from Robert, if so just wait for that.

**Comment by sirbacharach** [comment]
Checking over code now.

**Comment by sirbacharach** [comment]
All good, good to merge.

**Pull request merged**
